:data-uri:
:caption:
:sectanchors:
:toc: left
:toclevels: 2
:numbered:
:icons: font
:imagesdir: images
:last-update-label!:
:revnumber: {version}

= belgif-rest-problem

== Context

This is a Java library for working with https://www.belgif.be/specification/rest/api-guide/#error-handling[RFC 9457 standardized Belgif problems].

With this library, RFC 9457 Problems can be *automagically* treated as standard java exceptions:

* the server side can throw `io.github.belgif.rest.problem.api.Problem` exceptions (or subclasses), which are transparently converted to RFC 9457 compliant "application/problem+json" responses
* the client side can catch `io.github.belgif.rest.problem.api.Problem` exceptions (or subclasses), which are transparently thrown when an RFC 9457 compliant "application/problem+json" response is received

The library consists of these modules:

* *belgif-rest-problem*: library for RFC 9457 standardized Belgif problems
* *belgif-rest-problem-java-ee*: Java EE / Jakarta EE integration for belgif-rest-problem
* *belgif-rest-problem-spring-boot-2*: Spring Boot 2.x integration for belgif-rest-problem
* *belgif-rest-problem-spring-boot-3*: Spring Boot 3.x integration for belgif-rest-problem
* *belgif-rest-problem-validator*: validation library that generates Belgif-compliant BadRequestProblem with InputValidationIssues

== Release notes

include::release-notes.adoc[tag=recent-versions,leveloffset=1]

=== Older versions

See xref:release-notes.adoc[Release Notes].

[[getting-started]]
== Getting started

[[dependencies]]
=== Dependencies

[[dependencies-spring-boot]]
==== Spring Boot

[source,xml,role="primary",subs="attributes+"]
.Spring Boot 3 (Maven)
----
<dependency>
  <groupId>io.github.belgif.rest.problem</groupId>
  <artifactId>belgif-rest-problem-spring-boot-3</artifactId>
  <version>{revnumber}</version>
</dependency>
----

[source,role="secondary",subs="attributes+"]
.Spring Boot 3 (Gradle)
----
compile 'io.github.belgif.rest.problem:belgif-rest-problem-spring-boot-3:{revnumber}'
----

[source,xml,role="secondary",subs="attributes+"]
.Spring Boot 2 (Maven)
----
<dependency>
  <groupId>io.github.belgif.rest.problem</groupId>
  <artifactId>belgif-rest-problem-spring-boot-2</artifactId>
  <version>{revnumber}</version>
</dependency>
----

[source,role="secondary",subs="attributes+"]
.Spring Boot 2 (Gradle)
----
compile 'io.github.belgif.rest.problem:belgif-rest-problem-spring-boot-2:{revnumber}'
----

[[dependencies-jakarta-ee]]
==== Jakarta EE

[source,xml,role="primary",subs="attributes+"]
.Jakarta EE 9+ (Maven)
----
<dependency>
  <groupId>io.github.belgif.rest.problem</groupId>
  <artifactId>belgif-rest-problem-java-ee</artifactId>
  <version>{revnumber}</version>
  <classifier>jakarta</classifier>
</dependency>
----

[source,role="secondary",subs="attributes+"]
.Jakarta EE 9+ (Gradle)
----
compile 'io.github.belgif.rest.problem:belgif-rest-problem-java-ee:{revnumber}:jakarta'
----

[source,xml,role="secondary",subs="attributes+"]
.Java EE 8- (Maven)
----
<dependency>
  <groupId>io.github.belgif.rest.problem</groupId>
  <artifactId>belgif-rest-problem-java-ee</artifactId>
  <version>{revnumber}</version>
</dependency>
----

[source,role="secondary",subs="attributes+"]
.Java EE 8- (Gradle)
----
compile 'io.github.belgif.rest.problem:belgif-rest-problem-java-ee:{revnumber}'
----

[[getting-started-usage]]
=== Usage

At the core of this library lies an <<belgif-problem-types,exception hierarchy>> of Belgif-standardized problem types, with the possibility to define your own <<custom-problem-types,custom problem types>>.
Integration with Spring Boot and Jakarta EE works out of the box.

==== Returning a problem from a REST API

When implementing a REST API, returning a problem is as simple as throwing the problem exception from your application code:

[source,java,indent=0]
.Throwing a problem
----
include::../../../belgif-rest-problem/src/test/java/adoc/CodeSamples.java[tag=throw-problem]
----

==== Catching problems when calling a REST API

When calling a REST API, handling a problem is as simple as catching the problem exception in your application code:

[source,java,indent=0]
.Handling a problem on the client
----
include::../../../belgif-rest-problem/src/test/java/adoc/CodeSamples.java[tag=catch-problem]
----

NOTE: If the REST API returns a problem type for which you do not have a corresponding `@ProblemType` on your classpath, a link:apidocs/io/github/belgif/rest/problem/DefaultProblem.html[DefaultProblem] is thrown instead as fallback. See <<problem-type-registry>> for more details.

[[getting-started-spring-boot]]
=== Spring Boot

[WARNING]
====
As of version 6.0, Spring Framework also contains basic integration for RFC 9475 problem types. +
This is disabled by default, and MUST NOT be enabled.

* https://docs.spring.io/spring-boot/reference/web/servlet.html#web.servlet.spring-mvc.error-handling[spring.mvc.problemdetails.enabled]=false
* https://docs.spring.io/spring-boot/reference/web/reactive.html#web.reactive.webflux.error-handling[spring.webflux.problemdetails.enabled]=false
====

==== RestController

Problem exceptions and framework exceptions (including bean validation) thrown by RestController components are automatically converted to a proper RFC 9457 `application/problem+json` response.

WARNING: When using a Spring MVC annotation without name (e.g. `@RequestParam String name` instead of `@RequestParam("name") String name`), the parameter name for Bean Validation errors is retrieved via reflection as fallback.
For this to work, your application code must be compiled with the https://docs.oracle.com/en/java/javase/21/docs/specs/man/javac.html#option-parameters[-parameters] flag (see https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#parameters[maven-compiler-plugin]).
Otherwise, you will see parameter names like `arg0`.

InvalidRequestExceptions thrown by the link:https://bitbucket.org/atlassian/swagger-request-validator/src/master/[Atlassian swagger-request-validator] are also converted to a proper RFC 9457 `application/problem+json` response. Should this library be implemented in the same application.

WARNING: When this library is used in Spring Boot 2, `validation.request.path.missing` should be set to level IGNORE in order to return a 404 error for a missing path. (See documentation of the Atlassian library for more information.)

==== RestTemplate

Problem support is automatically enabled when constructing your RestTemplate through an autowired https://docs.spring.io/spring-boot/api/java/org/springframework/boot/web/client/RestTemplateBuilder.html[RestTemplateBuilder].

When manually constructing a RestTemplate instance, you'll need to apply the link:apidocs/io/github/belgif/rest/problem/spring/ProblemRestTemplateCustomizer.html[ProblemRestTemplateCustomizer] yourself.

==== Reactive WebClient

Problem support is automatically enabled when constructing your WebClient through an autowired https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/reactive/function/client/WebClient.Builder.html[WebClient.Builder].

When manually constructing a WebClient instance, you'll need to apply the link:apidocs/io/github/belgif/rest/problem/spring/ProblemWebClientCustomizer.html[ProblemWebClientCustomizer] yourself.

==== RestClient

Problem support is automatically enabled when constructing your RestClient through an autowired https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/client/RestClient.Builder.html[RestClient.Builder].

When manually constructing a RestClient instance, you'll need to apply the link:apidocs/io/github/belgif/rest/problem/spring/ProblemRestClientCustomizer.html[ProblemRestClientCustomizer] yourself.

[[getting-started-jakarta-ee]]
=== Jakarta EE

[WARNING]
====
While this library may work on other application servers, it has only been thoroughly tested on *JBoss EAP 7.4* (with MicroProfile XP 4.0) and *WildFly 31*.

Furthermore, the following dependencies are expected to be *"provided"* by the application server. If not, you'll need to add these dependencies to your application:

* com.fasterxml.jackson.core:jackson-databind
* org.slf4j:slf4j-api
====

==== JAX-RS service

Problem exceptions and framework exceptions (including bean validation) thrown by JAX-RS service components are automatically converted to a proper RFC 9457 `application/problem+json` response.

==== JAX-RS client

Problem support is automatically enabled for `@Inject`-ed `javax.ws.rs.client.Client(Builder)`.

When manually constructing a JAX-RS client instance, you'll need to wrap it yourself with `client = ProblemSupport.enable(client)`.

WARNING: JAX-RS async and reactive client API are https://github.com/belgif/rest-problem-java/issues/42[not fully supported] yet.

==== MicroProfile REST Client

Problem support is automatically enabled for MicroProfile REST Client.

==== RESTEasy Proxy Framework

Problem support must be manually enabled for https://docs.jboss.org/resteasy/docs/6.2.10.Final/userguide/#_client_proxies[RESTEasy Proxy Framework] by wrapping the proxy with `client = ProblemSupport.enable(client)`.

[[code-generators]]
=== Code generators

Code generators should be configured to use the belgif-rest-problem types for problem-related model classes, instead of generating them.

[[openapi-generator-maven-plugin]]
==== openapi-generator-maven-plugin

When using https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator-maven-plugin[openapi-generator-maven-plugin], configure `<schemaMappings>` as follows:

[source,xml,indent=0]
----
include::../../../belgif-rest-problem-it/belgif-rest-problem-codegen-it/pom.xml[tag=openapi-generator-maven-plugin]
----

[[swagger-codegen-maven-plugin]]
==== swagger-codegen-maven-plugin

When using https://github.com/swagger-api/swagger-codegen/tree/3.0.0/modules/swagger-codegen-maven-plugin[swagger-codegen-maven-plugin], configure `<importMappings>` as follows:

[source,xml,indent=0]
----
include::../../../belgif-rest-problem-it/belgif-rest-problem-codegen-it/pom.xml[tag=swagger-codegen-maven-plugin]
----

[[problems]]
== Problems

The https://www.belgif.be/specification/rest/api-guide/#error-handling[Belgif REST Guidelines] define a standard error handling approach, based on https://www.rfc-editor.org/rfc/rfc9457[RFC 9457 "Problem Details for HTTP APIs"].

The `belgif-rest-problem` library implements these standardized problem types as an exception hierarchy, with an abstract
link:apidocs/io/github/belgif/rest/problem/api/Problem.html[`io.github.belgif.rest.problem.api.Problem`] base class (containing the standardized "type", "href", "title", "status", "detail" and "instance" properties).

[subs="quotes"]
----
_Problem_
├── _ClientProblem_ (4xx)
|   └── _InputValidationProblem_ 1..* InputValidationIssue
├── _ServerProblem_ (5xx)
└── DefaultProblem (fallback)
----

[[belgif-problem-types]]
=== Belgif problem types

The package `io.github.belgif.rest.problem`
contains all problem types defined in the https://www.belgif.be/specification/rest/api-guide/#standardized-problem-types[Belgif REST Guidelines].

[subs="quotes"]
----
_Problem_
├── _ClientProblem_ (4xx)
|   ├── _InputValidationProblem_ 1..* InputValidationIssue
|   |   ├── *BadRequestProblem* (400)
|   |   ├── *MissingPermissionProblem* (403)
|   |   └── *ResourceNotFoundProblem* (404)
|   ├── *ExpiredAccessTokenProblem* (401)
|   ├── *InvalidAccessTokenProblem* (401)
|   ├── *NoAccessTokenProblem* (401)
|   ├── *MissingScopeProblem* (403)
|   ├── *PayloadTooLargeProblem* (413)
|   ├── *TooManyRequestsProblem* (429)
|   └── *TooManyFailedRequestsProblem* (429)
└── _ServerProblem_ (5xx)
    ├── *InternalServerErrorProblem* (500)
    ├── *BadGatewayProblem* (502)
    └── *ServiceUnavailableProblem* (503)
----

[NOTE]
====
* The `BadRequestProblem` is backwards compatible with the deprecated `InvalidParamProblem` _(with invalidParams[] instead of issues[])_ of openapi-problem 1.1.
* Besides the standard in/name/value properties for referencing a single input, the `InputValidationIssue` class also supports an inputs[] array for referencing multiple in/name/value inputs.
This is https://github.com/belgif/rest-guide/issues/108[not currently standardized].
* `MissingPermissionProblem` extending InputValidationProblem is https://github.com/belgif/rest-guide/issues/114[not currently standardized].
====

[[custom-problem-types]]
=== Custom problem types

Besides the standardized Belgif problem types, custom problem types can also be defined.

The https://www.belgif.be/specification/rest/api-guide/#rule-prb-type[naming convention] should be respected for custom problem type URIs:

* `urn:problem-type:<org>:<type>` for organization-wide problem types
* `urn:problem-type:<org>:<api>:<type>` for API-local problem types

[source,java,indent=0]
.Implementing an API-local custom problem type
----
include::../../../belgif-rest-problem/src/test/java/adoc/CodeSamples.java[tag=api-local-problem]
----

Your custom problem type can define additional properties if necessary.
For problem types related to input parameters, you can extend from `InputValidationProblem` instead of `Problem`.

IMPORTANT: Don't forget to add the `@ProblemType` annotation.

On *Jakarta EE* containers, custom problem types are discovered automagically through CDI.

On *Spring Boot*, only package `io.github.belgif.rest.problem` is scanned for @ProblemType annotations. +
Additional packages to scan can be configured in your application.properties:

[source,properties]
----
io.github.belgif.rest.problem.scan-additional-problem-packages=com.acme.custom
----

[[belgif-rest-problem-validator]]
== belgif-rest-problem-validator

The `io.github.belgif.rest.problem.validation.RequestValidator` can be used to perform validations on the input parameters of an API request.
This validation does not stop on the first invalid input.
It performs all configured validations and if any of them failed, a `BadRequestProblem` is thrown, containing each encountered `InputValidationIssue`.

[source,java,indent=0]
.RequestValidator
----
include::../../../belgif-rest-problem-validator/src/test/java/adoc/CodeSamples.java[tag=request-validator]
----

<1> validate SSIN structure
<2> validate enterprise number structure
<3> validate endDate >= startDate
<4> cross-parameter validation: either ssin or enterprise number should be present, but not both
<5> custom validations are also supported
<6> perform the configured validations, throws `BadRequestProblem` if any validations failed

.*Example BadRequestProblem* for invalid request `/resource?ssin=00000000000&enterpriseNumber=1111111111&startDate=2023-12-31&endDate=2023-01-01&password=oops`
[%collapsible]
====
[source,json]
----
{
  "type": "urn:problem-type:belgif:badRequest",
  "href": "https://www.belgif.be/specification/rest/api-guide/problems/badRequest.html",
  "title": "Bad Request",
  "status": 400,
  "detail": "The input message is incorrect",
  "issues": [
    {
      "type": "urn:problem-type:cbss:input-validation:invalidStructure",
      "title": "Input value has invalid structure",
      "detail": "SSIN 11111111111 is invalid",
      "in": "query",
      "name": "ssin",
      "value": "11111111111"
    },
    {
      "type": "urn:problem-type:cbss:input-validation:invalidStructure",
      "title": "Input value has invalid structure",
      "detail": "Enterprise number 2222222222 is invalid",
      "in": "query",
      "name": "enterpriseNumber",
      "value": "2222222222"
    },
    {
      "type": "urn:problem-type:cbss:input-validation:invalidPeriod",
      "title": "Period is invalid",
      "detail": "endDate should not preceed startDate",
      "inputs": [
        {
          "in": "query",
          "name": "startDate",
          "value": "2023-12-31"
        },
        {
          "in": "query",
          "name": "endDate",
          "value": "2023-01-01"
        }
      ]
    },
    {
      "type": "urn:problem-type:cbss:input-validation:exactlyOneOfExpected",
      "title": "Exactly one of these inputs must be present",
      "detail": "Exactly one of these inputs must be present: ssin, enterpriseNumber",
      "inputs": [
        {
          "in": "query",
          "name": "ssin",
          "value": "11111111111"
        },
        {
          "in": "query",
          "name": "enterpriseNumber",
          "value": "2222222222"
        }
      ]
    },
    {
      "type": "urn:problem-type:cbss:input-validation:example:invalidPassword",
      "title": "Invalid password",
      "in": "query",
      "name": "password",
      "value": "oops"
    }
  ]
}
----
====

[discrete]
[[extending-request-validator]]
=== Extending the RequestValidator

You may have a need to extend the RequestValidator with custom organization- or domain-specific validations. +
This is possible by extending the AbstractRequestValidator base class.

If in turn, you want your own validator implementation to be extensible as well, you can propagate the extensible fluent builder pattern as follows:

[source,java]
.Extensible request validator
----
 public abstract class AbstractMyRequestValidator<SELF extends AbstractMyRequestValidator<SELF>>
         extends AbstractRequestValidator<SELF> {

     public SELF something(Input<String> input) {
         addValidator(new SomethingValidator(input));
         return getThis();
     }

 }

 public final class MyRequestValidator extends AbstractMyRequestValidator<MyRequestValidator> {

 }
----

[[implementation-details]]
== Implementation details

This section describes the internal implementation details of this library.

[[problem-type-registry]]
=== @ProblemType and ProblemTypeRegistry

This library makes use of Jackson's https://github.com/FasterXML/jackson-docs/wiki/JacksonPolymorphicDeserialization[polymorphic deserialization] feature, so the Jackson ObjectMapper knows which problem type to instantiate when deserializing a problem.
The problem subclasses have their problem type URI configured in the
link:apidocs/io/github/belgif/rest/problem/api/ProblemType.html[`@ProblemType`] annotation.

These are discovered automagically by a link:apidocs/io/github/belgif/rest/problem/registry/ProblemTypeRegistry.html[`ProblemTypeRegistry`] implementation.

* in a *Jakarta EE* container, this is done by the link:apidocs/io/github/belgif/rest/problem/registry/CdiProblemTypeRegistry.html[`CdiProblemTypeRegistry`] CDI extension, integrated with the Jackson ObjectMapper by the CdiProblemModule.
* in a *Spring Boot* container, this is done by the link:apidocs/io/github/belgif/rest/problem/registry/SpringProblemTypeRegistry.html[`SpringProblemTypeRegistry`], integrated with the Jackson ObjectMapper by the SpringProblemModule.

When deserializing a problem for which no corresponding `@ProblemType` was found on the classpath, a link:apidocs/io/github/belgif/rest/problem/DefaultProblem.html[DefaultProblem] is used as fallback.

[[belgif-rest-problem-java-ee]]
=== belgif-rest-problem-java-ee

This module provides components that handle Java EE / Jakarta EE integration with the belgif-rest-problem library:

* *CdiProblemTypeRegistry:* ProblemTypeRegistry implementation that uses CDI component scanning to detect @ProblemType annotations.
* *CdiProblemModule:* a Jackson Module that registers the CdiProblemTypeRegistry.
* *ProblemObjectMapperContextResolver:* a JAX-RS ContextResolver for a Jackson ObjectMapper with the CdiProblemModule registered.
Its priority of "Priorities.USER + 200" allows it to be overridden if needed by the client application.
* *ConstraintViolationExceptionMapper:* a JAX-RS ExceptionMapper that converts ConstraintViolationException to an HTTP 400 BadRequestProblem.
* *ProblemExceptionMapper:* a JAX-RS ExceptionMapper that converts Problem exceptions to a proper application/problem+json response.
* *WebApplicationExceptionMapper:* a JAX-RS ExceptionMapper that handles WebApplicationExceptions thrown by the JAX-RS runtime itself, to prevent them from being handled by the DefaultExceptionMapper.
* *DefaultExceptionMapper:* a JAX-RS ExceptionMapper that converts any other uncaught exception to an HTTP 500 InternalServerErrorProblem.
* *JaxRsParameterNameProvider*: a bean validation ParameterNameProvider that retrieves parameter names from JAX-RS annotations

* *JAX-RS Client integration:*
** *ProblemClientResponseFilter:* JAX-RS ClientResponseFilter that converts problem response to a ProblemWrapper exception.
+
WARNING: In accordance with the spec, any exception thrown by a JAX-RS ClientResponseFilter gets wrapped in a ResponseProcessingException, unless the exception itself is a ResponseProcessingException.
For that reason, the ProblemClientResponseFilter wraps the Problem exception in a "ProblemWrapper" class that extends ResponseProcessingException.

** *ProblemSupport:* for programmatically enabling unwrapping of ProblemWrapper to Problem exceptions on a JAX-RS Client (also works for RESTEasy Proxy Framework clients).
+
[source,java]
----
private Client client = ProblemSupport.enable(ClientBuilder.newClient());
----

** *ProblemClientBuilderProducer:* makes ProblemSupport-enabled ClientBuilder and Client beans available for CDI @Inject
+
[source,java]
----
@Inject
public void setClient(Client client) {
    this.client = client;
}
----

* *MicroProfile REST Client integration:*
** *ProblemResponseExceptionMapper:* a ResponseExceptionMapper that converts problem responses to Problem exceptions.
** *ProblemRestClientListener:* a RestClientListener that registers the ProblemObjectMapperContextResolver and ProblemResponseExceptionMapper.
* *Jakarta EE 9+*: the main belgif-rest-problem-java-ee artifact targets Java EE (javax package namespace).
A secondary artifact that targets Jakarta EE 9+ (jakarta package namespace) is available with `<classifier>jakarta</classifier>`.

[[belgif-rest-problem-spring]]
=== belgif-rest-problem-spring

This module provides auto-configuration for components that handle Spring Boot integration with the belgif-rest-problem library:

* *SpringProblemTypeRegistry:* ProblemTypeRegistry implementation that uses classpath scanning to detect @ProblemType annotations.
By default, only package `io.github.belgif.rest.problem` is scanned for @ProblemType annotations.
Additional packages to scan can be configured in your application.properties:

[source,properties]
----
io.github.belgif.rest.problem.scan-additional-problem-packages=com.acme.custom
----

* *SpringProblemModule:* a Jackson Module that registers the SpringProblemTypeRegistry.
* *ProblemExceptionHandler:* an exception handler for RestControllers that handles the response serialization for Problem exceptions, and converts all other uncaught exceptions to an InternalServerErrorProblem.
* *BeanValidationExceptionsHandler:* an exception handler for RestControllers that converts bean validation related exceptions to HTTP 400 BadRequestProblem.
* *InvalidRequestExceptionHandler:* an exception handler for the link:https://bitbucket.org/atlassian/swagger-request-validator/src/master/[Atlassian swagger-request-validator] that converts InvalidRequestException to the correct Problem type.
* *RoutingExceptionsHandler:* an exception handler for RestControllers that converts routing related validation exceptions to HTTP 400 BadRequestProblem.
* *ProblemResponseErrorHandler:* a RestTemplate error handler that converts problem responses to Problem exceptions.
* *ProblemRestTemplateCustomizer:* a RestTemplateCustomizer that registers the ProblemResponseErrorHandler.
* *AnnotationParameterNameDiscoverer:* a bean validation ParameterNameDiscoverer that retrieves parameter names from Spring MVC annotations

In general, these components make it possible to use standard java exception handling (throw and try-catch) for dealing with problems in Spring Boot REST APIs.

[[belgif-rest-problem-spring-boot-2]]
==== belgif-rest-problem-spring-boot-2

Rather than depending on <<belgif-rest-problem-spring>> directly, Spring Boot 2.x users are recommended to depend on `belgif-rest-problem-spring-boot-2`, which adds some Spring Boot 2.x specific integrations:

* *ProblemWebClientCustomizer:* a WebClientCustomizer that registers a filter that converts problem responses to Problem exceptions.
This handles integration with the https://docs.spring.io/spring-framework/reference/web/webflux-webclient.html[Reactive WebClient].

[[belgif-rest-problem-spring-boot-3]]
==== belgif-rest-problem-spring-boot-3

Rather than depending on <<belgif-rest-problem-spring>> directly, Spring Boot 3.x users are recommended to depend on `belgif-rest-problem-spring-boot-3`, which adds some Spring Boot 3.x specific integrations:

* *ProblemWebClientCustomizer:* a WebClientCustomizer that registers a filter that converts problem responses to Problem exceptions.
This handles integration with the https://docs.spring.io/spring-framework/reference/web/webflux-webclient.html[Reactive WebClient].
* *NoResourceFoundExceptionHandler:* an exception handler for RestControllers that converts NoResourceFoundException to HTTP 404 ResourceNotFoundProblem.
* *ProblemRestClientCustomizer:* a RestClientCustomizer that registers the ProblemResponseErrorHandler.
