name: maven-release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Adopt OpenJDK 21
      uses: actions/setup-java@v5
      with:
        distribution: adopt
        java-version: '21'
        cache: maven
        server-id: central
        server-username: MAVEN_CENTRAL_USER
        server-password: MAVEN_CENTRAL_TOKEN
    - name: Login to registry.redhat.io
      uses: docker/login-action@v3.6.0
      with:
        username: ${{ secrets.REDHAT_REGISTRY_USER }}
        password: ${{ secrets.REDHAT_REGISTRY_TOKEN }}
        registry: registry.redhat.io
    - name: Build with Maven
      run: mvn ${{ runner.debug && '-X -e' || '' }} -B deploy -Drevision=${GITHUB_REF_NAME:1} -Prelease
      env:
        MAVEN_GPG_KEY: ${{ secrets.OPENAPI_OSSRH_GPG_SECRET_KEY }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.OPENAPI_OSSRH_GPG_SECRET_KEY_PASSWORD }}
        MAVEN_CENTRAL_USER: ${{ secrets.OPENAPI_OSSRH_USERNAME }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.OPENAPI_OSSRH_TOKEN }}
    - name: Publish doc
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/site
        destination_dir: ${{ github.ref_name }}
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        full_commit_message: Publish ${{ github.ref_name }} doc
    - name: Create release
      run: |
        gh release create ${GITHUB_REF} --draft --title "Release ${GITHUB_REF_NAME}" --notes "### Changes

        #### belgif-rest-problem-<module>
        
        * <item>

        [Documentation](https://belgif.github.io/rest-problem-java/${GITHUB_REF_NAME}/) | [Javadoc](https://belgif.github.io/rest-problem-java/${GITHUB_REF_NAME}/apidocs/)"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
