name: maven-release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Adopt OpenJDK 21
      uses: actions/setup-java@v4
      with:
        distribution: adopt
        java-version: '21'
        cache: maven
        server-id: ossrh
        server-username: OPENAPI_OSSRH_USERNAME
        server-password: OPENAPI_OSSRH_TOKEN
        gpg-private-key: ${{ secrets.OPENAPI_OSSRH_GPG_SECRET_KEY }}
        gpg-passphrase: OPENAPI_OSSRH_GPG_SECRET_KEY_PASSWORD
    - name: Login to registry.redhat.io
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.REDHAT_REGISTRY_USER }}
        password: ${{ secrets.REDHAT_REGISTRY_TOKEN }}
        registry: registry.redhat.io
    - name: Build with Maven
      run: mvn -X -B deploy -Drevision=${GITHUB_REF_NAME:1} -Prelease
    - name: Publish doc
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/site
        destination_dir: ${{ github.ref_name }}
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        full_commit_message: Publish ${{ github.ref_name }} doc
    - name: Create release
      run: |
        gh release create ${GITHUB_REF} --draft --title "Release ${GITHUB_REF_NAME}" --notes "Changes:
        - [placeholder]

        [Documentation](https://belgif.github.io/rest-problem-java/${GITHUB_REF_NAME}/) | [Javadoc](https://belgif.github.io/rest-problem-java/${GITHUB_REF_NAME}/apidocs/)"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
